list:
  core:
    require:
      - composer/installers
      - cweagans/composer-patches
      - drupal/core:^8.9
      - drupal/core-composer-scaffold:^8.9
      - drush/drush
    require-dev:
      - drupal-composer/drupal-security-advisories:dev-8.x-v2
      - drupal/core-dev:^8.9
      - ergebnis/composer-normalize
  devel:
    require-dev:
      - drupal/coder
      - drupal/console
      - drupal/devel
      - drupal/drupal-extension
  toolbar:
    require:
      - drupal/admin_toolbar
      - drupal/toolbar_themes