composer:
  drupal:
    type: 'project'
    minimum-stability: 'dev'
    prefer-stable: true
    config:
      sort-packages: true
    repositories:
      drupal:
        type: composer
        url: https://packages.drupal.org/8
    conflict:
      drupal/drupal: '*'
    extra:
      installer-paths:
        web/core:
          - type:drupal-core
        web/libraries/{$name}:
          - type:drupal-library
        web/modules/contrib/{$name}:
          - type:drupal-module
        web/profiles/contrib/{$name}:
          - type:drupal-profile
        web/themes/contrib/{$name}:
          - type:drupal-theme
        drush/Commands/contrib/{$name}:
          - type:drupal-drush
        web/modules/custom/{$name}:
          - type:drupal-custom-module
        web/themes/custom/{$name}:
          - type:drupal-custom-theme
        web/profiles/custom/{$name}:
          - type:drupal-custom-profile
        web/sites/{$name}:
          - type:drupal-drupal-multisite
        vendor/drupal/console/{$name}:
          - type:drupal-console
        vendor/drupal/console/language/{$name}:
          - type:drupal-console-language
        config/{$name}/sync:
          - type:drupal-config