name: Testing repository

on:
  push:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Start environment
      run: |
        sudo chown -R 1001:1000 .
        docker-compose up -d
        sleep 30

    - name: Composer cache
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Composer install
      run: |
        docker-compose exec -T web composer install --prefer-dist --no-progress --no-suggest --ansi

    - name: Check coding standards
      run: |
        docker-compose exec -T web composer test-phpcs

    - name: Initialize a Drupal composer.json
      run: |
        docker-compose exec -T -w ${PWD}/build web ../vendor/bin/robo drupal:extend --name="verbruggenalex/project" --description="Test project" -n

    - name: Test installing composer.json
      run: |
        docker-compose exec -T -w ${PWD}/build -e COMPOSER_MEMORY_LIMIT=-1 web composer install --no-progress --no-suggest --ansi

    - name: Run phpcs on build folder.
      run: |
        docker-compose exec -T -w ${PWD}/build web composer test-phpcs

    - name: Test installing Drupal
      run: |
        docker-compose exec -T -w ${PWD}/build web ./vendor/bin/drush si --db-url=mysql://root:@mysql:3306/drupal standard -y

    - name: Run behat tests on Drupal installation
      run: |
        docker-compose exec -T -w ${PWD}/build web composer test-behat
