name: Testing repository

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Start environment
      run: |
        sudo chown -R 1001:1000 .
        docker-compose up -d
        sleep 30

    - name: Composer cache
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Composer install
      run: |
        docker-compose exec -T web composer global update

    - name: Initialize a Drupal composer.json
      run: |
        docker-compose exec -T -w /home/docker/.composer/composer-drupal-plugin/build web taskman drupal:init -D build --name="vendor/project" --description="Test project" --author="Alex Verbruggen <verbruggenalex@gmail.com>" -n
